AWSTemplateFormatVersion: 2010-09-09
Description: Template to create infrastructure for pipeline deployment 
Resources:
  ImportedKeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: MyEC2KeyPair
      PublicKeyMaterial: ${CIRCLECI_PUBLIC_KEY} # Replace with the actual environment variable name from CircleCI
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      KeyName: !Ref ImportedKeyPair
      ImageId: 'ami-008fe2fc65df48dac' 
      InstanceType: t2.micro
  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
