AWSTemplateFormatVersion: 2010-09-09
Description: Template to create infrastructure for pipeline deployment
Parameters:
  SecurityKeyPair:
    Type: String
    Default: promsetup 
Resources:
  EC2InstancePrometheusServer:
    Type: 'AWS::EC2::Instance'
    Properties:
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      KeyName: !Ref SecurityKeyPair
      ImageId: 'ami-008fe2fc65df48dac' 
      InstanceType: t2.micro
      Tags:
        - Key: Name
          Value: 'prometheus_server'
  EC2InstancePrometheusNodeExporter:
    Type: 'AWS::EC2::Instance'
    Properties:
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      KeyName: !Ref SecurityKeyPair
      ImageId: 'ami-008fe2fc65df48dac' 
      InstanceType: t2.micro
      Tags:
        - Key: Name
          Value: 'prometheus_node_exporter'
    
  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Opening ports 9090, 9093, 9100 and SSH
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '9090'
          ToPort: '9090'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '9100'
          ToPort: '9100'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '9093'
          ToPort: '9093'
          CidrIp: 0.0.0.0/0
Outputs:
  NodeExporterPublicDNS:
    Value: !GetAtt EC2InstancePrometheusNodeExporter.PublicDnsName
   