AWSTemplateFormatVersion: 2010-09-09
Description: Template to create infrastructure for pipeline deployment
Parameters:
  ImportedKeyPair:
    Type: String
    Default: my-ansible-host 
Resources:
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      KeyName: !Ref ImportedKeyPair
      ImageId: 'ami-008fe2fc65df48dac' 
      InstanceType: t2.micro
      Tags:
        - Key: Name
          Value: !Sub 'my-app-server'
  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22 and HTTP connections
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
