version: '2.1'
orbs:
  aws-cli: circleci/aws-cli@4.0
jobs:
  aws-cli-example:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile_name: default
      - run: aws ec2 describe-instances
workflows:
  aws-cli:
    jobs:
      - aws-cli-example:
          context: ansible-aws
