version: '2.1'
orbs:
  aws-cli: circleci/aws-cli@4.0
jobs:
  create_infrastructure:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile_name: default
      - run: 
          name: Cloudformation script to create an Ec2 instance
          command: |
             aws cloudformation deploy --template-file template.yml --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5}
      - run:
          name: AWS CLI script to create inventory file
          command: |
             echo "[all]" > inventory
             aws ec2 describe-instances \
             --query 'Reservations[*].Instances[*].PublicIpAddress' \
             --output text >> inventory
             ls -ll
             cat inventory

workflows:
  aws-cli:
    jobs:
      - create_infrastructure:
          context: ansible-aws
