version: '2.1'
orbs:
  aws-cli: circleci/aws-cli@4.0
jobs:
  aws-cli-example:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile_name: default
      - run: 
          name: Describe all EC2 instances
          command: |
              touch inventory
              echo [all] > inventory
              aws ec2 describe-instances --query 'Reservations[*].Instances[*].PublicIpAddress' --filters "Name=tag:Project,Values=udacity" --output text >> inventory
              cat inventory
workflows:
  aws-cli:
    jobs:
      - aws-cli-example:
          context: ansible-aws
