version: '2.1'
orbs:
  aws-cli: circleci/aws-cli@4.0
commands:
  # Exercise: Reusable Job Code
  print_pipeline_id:
    parameters:
      id: 
        type: string
    steps:
      - run: echo << parameters.id >>

  # Exercise - Rollback
  destroy_environment:
    steps:
      - run:
          name: Destroy environment
          # ${CIRCLE_WORKFLOW_ID} is a Built-in environment variable 
          # ${CIRCLE_WORKFLOW_ID:0:5} takes the first 5 chars of the variable CIRCLE_CI_WORKFLOW_ID 
          when: on_fail
          command: |
            aws cloudformation delete-stack --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5}
jobs:
  create_infrastructure:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile_name: default
      - run: 
          name: Cloudformation script to create an Ec2 instance
          command: |
             aws cloudformation deploy --template-file template.yml --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5}
      - run:
          name: AWS CLI script to create inventory file
          command: |
             echo "[all]" > /tmp/inventory
             echo "Waiting for the EC2 instance to be in the running state..."
             INSTANCE_IDS=$(aws ec2 describe-instances \
             --query 'Reservations[*].Instances[?State.Name != `terminated` && Tags[?Key==`Name` && Value==`my-app-server`]].InstanceId' \
             --output json)
             echo $INSTANCE_IDS 
             INSTANCE_ID=$(echo $INSTANCE_IDS | jq -r 'flatten | select(. != null)[] | select(length > 0)' )

             echo "Instance ID: $INSTANCE_ID"

             aws ec2 wait instance-running --instance-ids $INSTANCE_ID

             echo "EC2 instance is now running."             
           
             PUBLIC_IP=$(aws ec2 describe-instances \
              --instance-ids $INSTANCE_ID \
              --query 'Reservations[*].Instances[*].PublicIpAddress' \
              --output text)
            
             echo "Public IP: $PUBLIC_IP"
             echo "$PUBLIC_IP" >> /tmp/inventory

      - persist_to_workspace:
          root: /tmp
          paths: 
            - inventory
      - destroy_environment
  configure_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["SHA256:+3VL1g52e8x9TZV+9yLDRkHMGPAe7IbDxHXYMue691M"]
      - attach_workspace:
          at: /tmp
      - run: 
          name: Install Ansible
          command: |
             apk add --update ansible
             apk add --update openssh
      - run:
          name: Run Playbook and Configure server
          command: |
             ansible-playbook -i /tmp/inventory main.yml -vvv 
      #- destroy_environment
  smoke_test:
    docker:
      - image: alpine:latest
    steps:
      - run: 
          name: Install curl
          command: |
             apk add --update curl
      - attach_workspace:
          at: /tmp
      - run:
          name: Smoke test
          command: |
            URL="http://$(grep -E -o '[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+' /tmp/inventory):3000"
            # Test if website exists
            if curl -s --head "${URL}" | head -n 1 | grep "200 OK" > /dev/null
            then
              exit 0
            else
              exit 1
            fi
            exit 1

      - destroy_environment
        when: on_fail

workflows:
  app-deployment:
    jobs:
      - create_infrastructure:
          context: ansible-aws
      - configure_infrastructure:
          requires: 
            - create_infrastructure
      - smoke_test:
          requires: 
            - configure_infrastructure
