version: '2.1'
orbs:
  aws-cli: circleci/aws-cli@4.0
jobs:
  create_infrastructure:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile_name: default
      - run: 
          name: Cloudformation script
          command: |
            aws ec2 describe-instances | jq -r '.Reservations[].Instances[]|.InstanceId+" "+.InstanceType+" "+(.Tags[] | select(.Key == "Name").Value)' 
           # aws cloudformation deploy --template-file template.yml --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} --parameter-overrides PublicKeyMaterial="${CIRCLECI_PUBLIC_KEY}"
workflows:
  aws-cli:
    jobs:
      - create_infrastructure:
          context: ansible-aws
