version: '2.1'
orbs:
  aws-cli: circleci/aws-cli@4.0
jobs:
  create_infrastructure:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile_name: default
      - run: 
          name: Describe all EC2 instances
          command: | 
          aws cloudformation deploy 
          --template-file template.yml 
          --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} 
workflows:
  aws-cli:
    jobs:
      - aws-cli-example:
          context: ansible-aws
